jobs:
  release:
    permissions:
      contents: "write"
    runs-on: ubuntu-24.04-arm
    steps:
      - name: "Checkout"
        uses: "actions/checkout@v7"
        with:
          fetch-depth: 0
          submodules: "recursive"
          token: "${{secrets.CODE_WRITE_TOKEN}}"
      - if: "github.event.inputs.update == 'true'"
        name: "Update submodules"
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git submodule update --remote
          if git diff --quiet; then
              echo "Submodules are the latest. Nothing to update."
              exit
          fi
          git add .
          git commit -m "chore: update submodules"
      - name: Test
        run: |
          set -euo pipefail
          sudo apt-get update
          sudo apt-get install --no-install-recommends -y git-buildpackage
          export DEBEMAIL="dev@radxa.com"
          export DEBFULLNAME='"Radxa Computer Co., Ltd"'
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          sudo apt-get install --no-install-recommends -y devscripts
          sudo apt-get build-dep -y .
          gbp dch --ignore-branch --multimaint-merge --release --spawn-editor=never \
            --git-log='--no-merges --perl-regexp --invert-grep --grep=^(chore:\stemplates\sgenerated)' \
            --dch-opt=--upstream --commit --commit-msg="feat: release %(version)s"
          export DEB_BUILD_OPTIONS=nocheck
          debuild -us -uc -b -Pnodoc
      - if: "github.event.inputs.release == 'true'"
        name: "Push"
        run: |
          git push
        shell: "bash"
name: "Create release"
"on":
  workflow_dispatch:
    inputs:
      release:
        default: true
        description: "Release new version"
        required: true
        type: "boolean"
      update:
        default: false
        description: "Update submodule"
        required: true
        type: "boolean"
permissions: {}
run-name: "${{ inputs.update && 'Update submodule' || '' }}${{ inputs.update && inputs.release && ' & ' || '' }}${{ inputs.release && 'Release new version' }}${{ !inputs.update && !inputs.release && 'Test for new release' || '' }}"
